---
- name: "Création de groupe"
  group:
          name: itescia
          state: present

- name: "Création d'un utilisateur"
  user:
          name: "itesciadmin"
          password: '!'
          groups: sudo, itescia
          state: present
          createhome: yes
          home: /home/itesciadmin

- name: "SSH autorisé"
  authorized_key:
          user: itescia
          state: present
          key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCjc0bzD0hkwd7MdQP59h6bTyxus5udNRrxVz2PXe1r8NyTVz7n25mG2Iop+Z0dKpfLTiDrV7pOwLLkyjOKGf8hq/wYl6btmSpJqPXPBiawGZZ1m7zqygHWkYjZnf2my7Y$'

- name: "Supression d'un utilisateur existant"
  user:
          name: itescia
          state: absent
          remove: yes
